workflows:
  ios-app-store-build:
    name: iOS App Store Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: jp.soni08.taiatarigame
      node: 20
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --clean
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up Xcode Code Signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - soni0844@gmail.com
